# You can override these default settings with a local.toml file. 
# You can also load even more overrides from a toml file with the same name as the run_mode.  e.g. dev.toml
#
# DO NOT STORE SECRETS IN THIS FILE!  INSTEAD CREATE YOUR OWN local.toml or run mode toml FILE AND OVERRIDE THESE SETTINGS THERE.

[website]
bind_ssl_config = { enabled = false }
bind_ports = { http = 8080 }
public_ports = { http = 8080 }

[calculator_config]
first_number = 5
second_number = 6
